### ISSUE TITLE
Please provide How do i change admin password?

### ISSUE THREAD

**Issue by sergeymeleschenko** [itiligent/OpenVAS-GVM-Install#4]
Please provide How do i change admin password?

**Comment by itiligent** [comment]
Although this is not a project issue and a GVM support topic, the answer is buried quite deep in GVM forums. 

Another way to build familiarity is to search scripts.  In this case this appproach will lead you lines that realte to users and the gvmd executable, which you can then query for options.. eg:  sudo  /usr/local/sbin/gvmd --help 

And from there, your can deduce changing a password is:  
`sudo /usr/local/sbin/gvmd --user=adminuser --new-password=newpassword`

I've added this above command reminder to the final script on screen output.

**Comment by sergeymeleschenko** [comment]
Thanks for your answer. 

Please double-check. I think it's a bug. 

Try to enter container docker exec -it greenbone-community-edition-gvmd-1 bash
Than udo /usr/local/sbin/gvmd --user=adminuser --new-password=newpassword

Than on login page I got message 

The Greenbone Vulnerability Manager service is not responding. This could be due to system maintenance. Please try again later, check the system status, or contact your system administrator.

And can't log in

**Comment by itiligent** [comment]
Oh I see, I assumed you were installing from the source , not with Docker .

Still not a bug. If you are using Docker you have to execute things differently. Again, if you look at what scripts are doing, you will find this line in the build scipt that is downloaded from GVM....and therein lies your answer. Adapt to suit your path to the compose file path and name:.  

`docker compose -f $DOWNLOAD_DIR/docker-compose-$RELEASE.yml -p greenbone-community-edition \
    exec -u gvmd gvmd gvmd --user=admin --new-password=$password`

(As I mention in the readme, the Docker version is not very reliable and I get the feeling not a lot of QA goes into this before each update. Also, I checked in on this today, and a few architectural things have changed with the build dependecy and process since I put this together, so I'll put out an updated source biuld script soon (source build is a far better and more solid option)

**Comment by sergeymeleschenko** [comment]
Many thanks. Sorry to bother you.
